### ISSUE TITLE
Displaying nvd3Plot() plots in Shiny

### ISSUE THREAD

**Issue by alaneng-zz** [ramnathv/rChartsShiny#3]
I've got another question --

With the rPlot(), under ui.R I simply have to pass the identifier over to showOutput. Say the identifier is "chart", then I'd pass that to showOutput("chart", "polycharts").

Regarding nvd3Plot(), how would I go about displaying the plot in Shiny? showOutput() didn't work for me.

Thanks!

Alan

**Comment by ramnathv** [comment]
It should work the same way. `showOutput('chart', 'nvd3')`. If you can post some reproducible code, I can take a closer look. Here is a [sample Shiny app](https://gist.github.com/ramnathv/5531732). You can run it by typing `runGist("5531732")`

**Comment by alaneng-zz** [comment]
The solution here was the second argument to showOutput, 'nvd3'. Thanks, it worked!

**Comment by ramnathv** [comment]
Great.

**Comment by sf99167** [comment]
Can NVD3 render candle stick charts as well i.e OHLC??
