### ISSUE TITLE
Interactive Visualizations with rCharts and Shiny: problems with Input

### ISSUE THREAD

**Issue by thierrymartens** [ramnathv/rChartsShiny#5]
I am trying to reproduce the shiny app as described [here](http://ramnathv.github.io/rChartsShiny/)
However, when using 

```
choices = sort(unique(dat2m$country))
```

I get the numbers 1 to 35 as possible choices, **NOT** the names of the countries (as one would expect).
If I use

```
choices = c("Belgium","Canada")
```

it does display these two countries correctly...

I am working on a Windows 7 platform,
using RStudio Version 0.98.1102,
rCharts 0.4.5,
and Shiny 0.11.1

**Comment by ramnathv** [comment]
I presume you were able to solve it based on your comment on the PR.
